version: "2"
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.7-management
    ports:
        - "5672:5672"
        - "15672:15672"
    restart: always

  prometheus:
    image: prom/prometheus:v2.19.2
    ports:
      - "9090:9090"
    volumes:
      - type: bind
        source: ./prometheus.yml
        target: /etc/prometheus/prometheus.yml
  example_ms:
    build: .
    depends_on:
      - rabbitmq
    ports:
      - "8000:8000"
